name: Zig Install Workflow
inputs:
  version:
    default: 'master'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
    - name: Install Zig
      run: |
        curl -L https://github.com/marler8997/zigup/releases/download/v2024_05_05/zigup-x86_64-linux.tar.gz | tar xz
        echo "Install"
        sudo ./zigup ${{ inputs.version }} --install-dir /usr/bin
      shell: bash
