name: Zig Install Workflow

on:
  workflow_call:
    inputs:
      version:
        default: 'master'
        required: false
        type: string

jobs:
  install:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Setup Zig
        run: |
          echo ${{ inputs }}
          curl -L https://github.com/marler8997/zigup/releases/download/v2024_05_05/zigup-x86_64-linux.tar.gz | tar xz
          ./zigup ${{ inputs.version }}
          zig build --fetch
